/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Project, ServiceItem, FeedItem, PressItem } from './types';

export const projects: Project[] = [
  {
    id: 'behind-design',
    title: 'Behind Design (Thesis)',
    client: 'UID Art Direction Curation',
    year: '2022',
    image: '/src/assets/images/kalamkaar_poster_1780159351293.png',
    category: 'Branding, Art Direction, Motion Graphics',
    description: '"Behind Design" is a branding project that aims to create a cohesive and engaging identity for a new podcast that promises to be a valuable resource for anyone interested in the world of design in India.',
    role: 'Art Director & Designer',
    deliverables: ['Identity System Design', 'Pristine Brand Playbooks', 'Motion Campaign Assets'],
    color: 'bg-[#ECE7DC]',
    textColor: 'text-neutral-900',
    hasDetails: true,
  },
  {
    id: 'disney-shopping-app',
    title: 'Disney Shopping App',
    client: 'College Disney Showcase',
    year: '2021',
    image: '/src/assets/images/kama_iphone_1780154940227.png',
    category: 'UI/UX',
    description: 'This Project is a E-commerce Application for the existing Disney Shopping website which offers Disney official Merch',
    role: 'Lead UI/UX Designer',
    deliverables: ['High-Fidelity Figma Systems', 'Shop Checkout Layouts', 'Interactive Micro-Prototyper'],
    color: 'bg-[#F9D043]',
    textColor: 'text-black',
    hasDetails: true,
  },
  {
    id: 'artist-management',
    title: 'Artist Management',
    client: 'Tcules UI/UX Placement Task',
    year: '2023',
    image: '/src/assets/images/zave_fintech_app_1780157917788.png',
    category: 'UI/UX, Web Design',
    description: 'An Event/Artist Management interface for the event organizers where the organizer can see the status of the information that they requested from each manager of the bands performing.',
    role: 'UI/UX Designer',
    deliverables: ['Web Interface Design', 'Dashboard Layouts', 'User Flow Diagrams'],
    color: 'bg-[#6E8FEA]',
    textColor: 'text-white',
    hasDetails: true,
  },
  {
    id: 'grace',
    title: 'Grace',
    client: 'Fashion Branding Studio',
    year: '2021',
    image: '/src/assets/images/dwan_music_visuals_1780157941722.png',
    category: 'Branding, Art Direction, Packaging',
    description: 'Grace is a fashion branding project that focuses on luxury formal attires for females.',
    role: 'Brand Designer',
    deliverables: ['Brand Identity System', 'Packaging Design', 'Lookbook Curation'],
    color: 'bg-[#ECE7DC]',
    textColor: 'text-neutral-900',
    hasDetails: true,
  },
  {
    id: 'wild-young',
    title: 'Wild + Young',
    client: 'Marketing Agency Concept',
    year: '2022',
    image: '/src/assets/images/headspace_billboard_1780154913817.png',
    category: 'Branding, Motion Graphics',
    description: 'Wild + Young is a online marketing agency concept branding project that targets young influencers to manage them.',
    role: 'Brand Designer',
    deliverables: ['Brand Identity', 'Motion Graphics', 'Social Media Assets'],
    color: 'bg-[#6E8FEA]',
    textColor: 'text-white',
    hasDetails: true,
  },
  {
    id: 'brand-work',
    title: 'Brand Work & Collabs',
    client: 'Royal Enfield, Zave, Kalamkaar',
    year: '2023-Present',
    image: '/src/assets/images/re_helmet_design_1780157894631.png',
    category: 'Product, Decals & SaaS Identity',
    description: 'Segregated overview showing collaborations with high-growth entities, designing helmet decals, marketing illustrations, and posters.',
    role: 'Creative Collaborator',
    deliverables: ['Industrial Helmet Decals', 'Fintech Card Illustrations', 'Promo Graphic Campaigns'],
    color: 'bg-[#BAC6F5]',
    textColor: 'text-black',
    hasDetails: true,
  },
  {
    id: 'motion-shorts',
    title: 'Motion Shorts',
    client: 'Motion & Animation Loops',
    year: '2024',
    image: '/src/assets/images/motion_frame_shapes_1780159369545.png',
    category: '2D Animation Loops',
    description: 'Directing all elements of 2D dynamic layouts, timeline animations, and typographic motion with custom bezier speed curves.',
    role: 'Lead Motion Illustrator',
    deliverables: ['60fps Vector Sequence', 'Keyframe Storyboard Timeline', 'Custom Ease Curve Presets'],
    color: 'bg-[#BAC6F5]',
    textColor: 'text-black',
    hasDetails: true,
  },
  {
    id: 'grad-project',
    title: 'Graduation Project',
    client: 'Thesis Research film',
    year: '2023',
    image: '/src/assets/images/zave_ui_system_1780159329350.png',
    category: 'Graduation Motion Graphics',
    description: 'A longer motion graphics narrative investigating transitional milestones, complete with research notes and model sheets.',
    role: 'Director & Researcher',
    deliverables: ['Cinematic Storyboards', 'Character Model Sheets', 'Methodology Publications'],
    color: 'bg-[#AA89E5]',
    textColor: 'text-white',
    hasDetails: true,
  },
  {
    id: 'small-projects',
    title: 'Smaller Projects',
    client: 'Experimental Artroom',
    year: '2022-2023',
    image: '/src/assets/images/spatial_exhibit_1780159389308.png',
    category: 'Design Lookbooks & Posters',
    description: 'Collection of minor design sprints, experimental layout sheets, lookbook curations, and asymmetrical graphic collages.',
    role: 'Visual Consultant',
    deliverables: ['Grace Fashion Lookbook', 'Wild + Young Print plates', 'Spatial Curation Systems'],
    color: 'bg-[#ECE7DC]',
    textColor: 'text-neutral-900',
    hasDetails: true,
  },
];

export const services: ServiceItem[] = [
  {
    id: 'art-direction',
    name: 'Art Direction',
    description: 'Directing visual architectures, editorial pacing, and unifying high-growth digital lookbooks.',
    skills: ['Brand Vision', 'Creative Direction', 'Visual Aesthetics', 'Style Playbooks'],
  },
  {
    id: 'brand-identity',
    name: 'Brand Identity',
    description: 'Building cohesive visual languages that communicate core values across digital and physical mediums.',
    skills: ['Logo Systems', 'Color Theory', 'Graphic Standards', 'Asset Kits'],
  },
  {
    id: 'illustration',
    name: 'Illustration',
    description: 'Developing high-impact custom characters and friendly commercial graphics with personality.',
    skills: ['Vector Art', 'Character Design', 'Storyboarding', 'Creative Assets'],
  },
  {
    id: 'ui-app-design',
    name: 'UI/App Design',
    description: 'Translating complex user journeys into structured layouts, neat grids, and frictionless screens.',
    skills: ['Figma Systems', 'Mobile Interface', 'Prototyping', 'Checkout Flows'],
  },
  {
    id: 'web-design',
    name: 'Web Design',
    description: 'Formulating responsive editorial desktop frameworks with balanced typographic flow.',
    skills: ['Grid Precision', 'Layout Hierarchy', 'Responsive Styling', 'Portfolio Curation'],
  },
  {
    id: 'animation-direction',
    name: 'Animation Direction',
    description: 'Giving designs dynamic momentum through frame sequencing, smooth eases, and snappy transitions.',
    skills: ['After Effects', 'Kinetic Web', 'Motion Guidelines', 'Story Reels'],
  },
];

export const feedItems: FeedItem[] = [
  {
    id: 'f1',
    image: '/src/assets/images/re_helmet_design_1780157894631.png',
    alt: 'Helmet Decal Details',
    caption: 'Helmet shell illustration styling—concept decal work exploring modern line dynamics and sports typography.',
    tag: 'Product Concept',
    ratio: 'aspect-[3/4]',
  },
  {
    id: 'f2',
    image: '/src/assets/images/zave_ui_system_1780159329350.png',
    alt: 'Geometric UI Components',
    caption: 'Fintech card illustration system exploration—infusing personality into transactional screens and empty states.',
    tag: 'Interface Art',
    ratio: 'aspect-[1/1]',
  },
  {
    id: 'f3',
    image: '/src/assets/images/kalamkaar_poster_1780159351293.png',
    alt: 'Experimental Poster Layout',
    caption: 'Kalamkaar Music visual concept—typography and layout study for digital music single release campaigns.',
    tag: 'Graphic Poster',
    ratio: 'aspect-[3/4]',
  },
  {
    id: 'f4',
    image: '/src/assets/images/motion_frame_shapes_1780159369545.png',
    alt: 'Abstract Motion Graphic Frame',
    caption: 'Explaining application features via 2D abstract shapes—motion sequence frame detailing corporate SaaS value.',
    tag: 'Motion Framing',
    ratio: 'aspect-[3/4]',
  },
  {
    id: 'f5',
    image: '/src/assets/images/spatial_exhibit_1780159389308.png',
    alt: 'Spatial Design Exhibition Graphics',
    caption: 'Visual installation layout setup—physical exhibition space graphic mapping and display curation.',
    tag: 'Spatial Design',
    ratio: 'aspect-[1/1]',
  },
];

export const pressItems: PressItem[] = [
  {
    id: 'p1',
    publisher: 'On Design Podcast',
    date: 'Oct 2022',
    title: 'Aryan Abhishek on Headspace, sex, death and character design',
    url: 'https://www.cumulusassociation.org',
  },
  {
    id: 'p2',
    publisher: 'The AOI',
    date: 'Mar 2021',
    title: 'How to get into branding illustration',
    url: 'https://www.instagram.com',
  },
  {
    id: 'p3',
    publisher: 'Creative Review',
    date: 'Aug 2023',
    title: 'Using illustration in branding: a how to',
    url: 'https://www.royalenfield.com',
  },
  
  {
    id: 'p5',
    publisher: 'UID Ahmedabad',
    date: 'Apr 2023',
    title: 'Representing Bachelors in Design (B.Des) Thesis Projects and Visual Communication curation guidelines',
    url: 'https://www.uid.edu.in',
  },
];
